### ISSUE TITLE
Publish release for version 1.2.4

### ISSUE THREAD

**Issue by Regaez** [dukt/social#1]
I noticed there are only 2 releases of this plugin available via Github, and they're both for the Craft 3 beta. Could you please publish a release of version **1.2.4**? 

I'd like to be able to reliably download that specific version of the social plugin for my Craft 2.6 instances. The https://dukt.net/social/download link currently serves 1.2.4, but does not guarantee that specific version in the future. 

Thanks!

**Comment by benjamindavid** [comment]
Thanks for the feedback @Regaez!

It's a work in progress, we've just made all of our Craft 3 plugins available on public repos, Craft 2 plugins are next.

**Comment by benjamindavid** [comment]
Social v1 branch is now publicly available: https://github.com/dukt/social/tree/v1

**Comment by Regaez** [comment]
Awesome! Thanks a lot!
