### ISSUE TITLE
Facebook app review for user_location permission

### ISSUE THREAD

**Issue by carolfalardeau** [dukt/social#10]
### Description

Facebook need to review the app to use the user_location permission.
https://developers.facebook.com/docs/facebook-login/permissions/#reference-user_location

Can you add an option in the plugin to remove the permission and everything that is related to?
We don't need this permission for our website.

Thank you

### Additional info

- Plugin version: 1.2.4
- Craft version: 2.6.3015
- PHP version: 7.1.4

**Comment by benjamindavid** [comment]
@carolfalardeau Thanks for reporting, [Social 1.2.7](https://github.com/dukt/social/releases/tag/1.2.7) has just been released and drops `user_location` as a default scope.

That change is also coming in the next release of [Social 2](https://github.com/dukt/social) beta.
