### ISSUE TITLE
Ability to set up remember me configuration 

### ISSUE THREAD

**Issue by YongYu123** [dukt/social#12]
### Description
I'm using this social plugin and found the user who uses the social login will log out after one day. Are there any configuration can set up to keep user login? Such as the remember me.

### Additional info

- Plugin version:  2.0.0-beta.10
- Craft version: Craft Pro 3.0.13.2
- PHP version:  7.2.5
- Database driver & version: PostgreSQL 10.3
- Plugins & versions:

**Comment by benjamindavid** [comment]
Closing this to keep the discussion going in https://github.com/dukt/social/issues/17. Thanks!
