### ISSUE TITLE
Plugin broken on update to beta10

### ISSUE THREAD

**Issue by samhibberd** [dukt/social#13]
### Description

Settings are not being read from the config files or allow update in the CP.

### Steps to reproduce

1. Update to beta 10, settings now no longer configured and broken.

### Additional info

- Plugin version: beta10
- Craft version: 3.0.17.1
- PHP version: 7.1
- Database driver & version: 
- Plugins & versions:

**Comment by benjamindavid** [comment]
The structure of the config array has changed a bit since beta 10:
https://docs.dukt.net/social/v2/configuration.html#loginproviders

Feel free to reopen if you're still encountering issues after updating your config array.
