### ISSUE TITLE
Can't retrieve Socialuid for facebook login

### ISSUE THREAD

**Issue by lforeverl** [dukt/social#15]
Before updating to version Social 2.0.0-beta.10 from Social 2.0.0-beta.6 we used the following code to make an authorization from the mobile app.
Currently, we made the changes to social.php and our API to allow Twitter login, but Facebook login isn't working because the "Socialuid" is in a protected data array.
We can't receive the Socialuid to compare it whether the id is already in the system or not.

The received error is:
![photo_2018-08-05_16-25-03](https://user-images.githubusercontent.com/27344972/43685410-2c28d112-98cc-11e8-856e-75557908b305.jpg)

This is the code that was used and working before the update.

`function registerOrLoginFromToken(Token $token)
{
    $socialLoginProvider = Social::getInstance()->getLoginProviders()->getLoginProvider($token->providerHandle);
    $attributes = $socialLoginProvider->getProfile($token);

    $socialUid = $attributes['id'];

    $account = Social::getInstance()->getLoginAccounts()->getLoginAccountByUid($socialLoginProvider->getHandle(), $socialUid);
    // Existing user
    if ($account) {
        $craftUser = Craft::$app->users->getUserById($account->userId);
        if ($craftUser) {
            Craft::$app->elements->saveElement($account);

            login($craftUser, $account, $token);
            return true;
        }
        throw new Exception("Social account exists but Craft user doesn't");
    }
    // Register new user
    $craftUser = registerUser($attributes, $socialLoginProvider->getHandle());
    if ($craftUser) {
        // Save social user
        $account = new LoginAccount;
        $account->userId = $craftUser->id;
        $account->providerHandle = $socialLoginProvider->getHandle();
        $account->socialUid = $socialUid;

        Craft::$app->elements->saveElement($account);

        login($craftUser, $account, $token, true);
        return true;
    }

    throw new Exception("Craft user couldn’t be created.");
}`

- Plugin version: Social 2.0.0-beta.10
- Craft version: Craft Pro 3.0.1
- PHP version: 7.1.19
- Database driver & version: MySQL 5.6.40
- Plugins & versions:

**Comment by benjamindavid** [comment]
Hey @lforeverl,

The social UID is automatically handled by the plugin so you don't have to add anything to your `social.php`. If you're still having issues, feel free to reopen this issue and attach your config and the errors from your logs folder.
