### ISSUE TITLE
Error when saving settings

### ISSUE THREAD

**Issue by skoften** [dukt/social#16]
<img width="1032" alt="screen shot 2018-08-22 at 14 35 57" src="https://user-images.githubusercontent.com/1286410/44463671-c9363900-a618-11e8-86e1-9fb32e702168.png">

Craft CMS 3.0.20
PHP 7.0.30-0ubuntu0.16.04.1

Edit: after this "fix" the saving error is gone, but the form won't save the values though (https://github.com/dukt/social/pull/14/commits/f7e702b4b89ae72aaafbc34f6352aecf2db079ed)

**Comment by benjamindavid** [comment]
Fixed by https://github.com/dukt/social/pull/14. Thanks @skoften!
