### ISSUE TITLE
User session not saved (rememberMe)

### ISSUE THREAD

**Issue by skoften** [dukt/social#17]
When you login via Facebook or Twitter, the user gets logged out after a while. Don't know the exact time, but I did a test and logged in via Twitter yesterday and 12 hours later I refreshed the browser and the user was logged out.

Normally a user can check the rememberMe-field, but this seems to be skipped when logging in via the social plugin.

How can we prevent users getting logged out? 

Thanks!

**Comment by benjamindavid** [comment]
The plugin is using the `userSessionDuration` config for the duration of the session. I'll look into making it support the `rememberedUserSessionDuration` config. Thanks!

**Comment by benjamindavid** [comment]
Adding a remember me checkbox to the Social login process could actually be a bit confusing as social login buttons are usually placed next to a login form which already has a similar feature. Maybe we should add a new `socialUserSessionDuration` config instead to allow customization of the session duration for social users.

**Comment by benjamindavid** [comment]
@skoften Did you try to extend your `userSessionDuration` config a bit so that it lasts more than 12 hours? If you want that for Social users, you'd probably want that for other users as well right?

**Comment by skoften** [comment]
Hi,

Changing rememberedUserSessionDuration and userSessionDuration seem to have fixed it, thanks!

**Comment by benjamindavid** [comment]
Great! Please note that only `userSessionDuration` will have an effect on the duration of Social users' session.
