### ISSUE TITLE
Locked domain cause error

### ISSUE THREAD

**Issue by pierrestoffe** [dukt/social#19]
### Description

I noticed that the plugin wasn't able to register new users as soon as I added locked domains.

### Solution

From what I could find the issue is probably located in the `checkLockedDomains` function. A match is made between the account email and the locked domain but the account email is null.

I create a PR with the solution I found https://github.com/dukt/social/pull/18.

### Additional info

- Plugin version: 2.0.0-beta.12
- Craft version: 3.0.21
- PHP version: 7.2

**Comment by benjamindavid** [comment]
Thanks for pointing this out @pierrestoffe!
