### ISSUE TITLE
facebook authorization not working

### ISSUE THREAD

**Issue by S1lentium** [dukt/social#2]
When auth via facebook i get an error:
OAuthException: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

Redirect uri: http://cms.iloveqatar.net:2052/index.php?p=actions/social/login-accounts/callback
This uri is same on facebook settings.
I think problem is on uri parameters, where facebook not recive backslahes on uri parameters. When i change manually uri to  http://cms.iloveqatar.net:2052/callback, it is working. But i can't change uri on settings of social plugin

**Comment by benjamindavid** [comment]
@S1lentium Which version of Social are you using v1 or v2?

**Comment by S1lentium** [comment]
v2

**Comment by benjamindavid** [comment]
Fixed by https://github.com/dukt/social/commit/6dda6c517af761cce7dbbed1c4f04375c1391a09.

Thanks for reporting the issue!

**Comment by jschutt** [comment]
Any chance you'll port this back to v1 of the plugin? 👍
