### ISSUE TITLE
Facebook login to CP on multi-site

### ISSUE THREAD

**Issue by Djive** [dukt/social#21]
This is a Craft PRO multi-site setup. 
Don't have any website registrations and logins at the moment, only login to CP.
Did a setup for Facebook Social Login and everything checks out.
Default User Group that users will be added to when registering with a social service is group with access to CP.

But when trying to log in as a new user, getting the following error:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'targetId' cannot be null The SQL being executed was: INSERT INTO `craft_relations` (`fieldId`, `sourceId`, `sourceSiteId`, `targetId`, `sortOrder`, `dateCreated`, `dateUpdated`, `uid`) VALUES (7, 2183, NULL, NULL, 1, '2018-10-26 13:03:40', '2018-10-26 13:03:40', 'f89f391f-c569-4e87-b1e3-466ef24fe841')

- Plugin version: 2.0.0-beta.14
- Craft version: Craft CMS 3.0.28
- PHP version: 7.2.10
- Database driver & version: MySQL 5.6.38

Thanks!

**Comment by benjamindavid** [comment]
Are you still experiencing this issue?
