### ISSUE TITLE
Add OAuth token to profile response?

### ISSUE THREAD

**Issue by chrisrowe** [dukt/social#22]
I'd like to be able to store a new users auth token to their profile to be able to make future API calls to the provider. I've managed to hack this in but would you consider adding it as a feature, or adding an event I can hook to make this cleaner?

**Comment by chrisrowe** [comment]
(╭☞   ͡° ͜ʖ ͡° )╭☞

**Comment by benjamindavid** [comment]
Ahah cool 😉! Just keep in mind the plugin does absolutely nothing to keep these tokens active, in fact, they are just being used at login or registration and are never stored to the database.

Thanks for the feedback!

**Comment by philipzaengle** [comment]
This would be a nice addition.
