### ISSUE TITLE
Facebook login redirect added "#_=_" to the end of url

### ISSUE THREAD

**Issue by xhuang9** [dukt/social#24]
### Description
Facebook login redirect, added `"#_=_"` to the end of the url
For example, Url is `"example.com/entry/entry-1-slug"`
The redirect url will be `"example.com/entry/entry-1-slug#_=_"`

Turns out more people have encountered this error:
`https://stackoverflow.com/questions/7131909/facebook-callback-appends-to-return-url`

I have temporary fix this using the javascript suggested in the link.

### Steps to reproduce
1. create a craft section.
2. set the section url to be {{siteUrl}}anything/{slug}
In template having code:

`{% set SocialRedirect = entry.uri %}`
`<a herf="{{ craft.social.getLoginUrl('facebook', { redirect: SocialRedirect }) }}">Facebook Login</a>`

Addtional:
User field mapping is:

id | {{ profile.getId() }}
email | {{ profile.getEmail() }}
username | {{ profile.getEmail() }}
photo | {{ profile.getPictureUrl() }}
displayName | {{ profile.getName() }}
firstName | {{ profile.getFirstName() }}
lastName | {{ profile.getLastName() }}

### Additional info

- Plugin version: 2.0.0-beta.12
- Craft version: 3.0.31
- PHP version: 7.1
- Database driver & version: 5.7.22 for linux (x86_64)
- Server Info: AWS linux version 1

**Comment by benjamindavid** [comment]
Thanks for the suggested solution @xhuang9!

`#_=_` should only be added if the redirect URL is not provided, but Facebook doesn't seem to be in a hurry to fix this bug that has been around for ages. 🤞
