### ISSUE TITLE
Saving the record twice

### ISSUE THREAD

**Issue by mariendries** [dukt/social#26]
### Description

In the element you are using the afterSave event to update the social_login_accounts table when an element is updated, which makes perfect sense,
But in the service "LoginAccounts" you are also calling the "save" function on the accountRecord (line 142) after the element is saved.
To me it looks like you are doing the same thing (updating the DB) twice, is this on purpose?

**Comment by benjamindavid** [comment]
Login accounts were not really saved twice, but that `dukt\social\services\LoginAccounts::saveLoginAccount()` method didn't really make sense anymore. Thank you @mariendries!
