### ISSUE TITLE
google login doesn't redirect

### ISSUE THREAD

**Issue by DidoMarchet** [dukt/social#27]
### Description
Hi,
I'm trying to login with Google but when comes the login screen and I click my account it doesn't redirect correctly but reload the same screen.
I've created the app, I've configurated 0Auth into the cp and activated the google login.
I've setup facebook login without any issue.

If you have any idea about my issue thanks in advance.

Regards,

Davide

**Comment by benjamindavid** [comment]
Hey @DidoMarchet, do you get any errors in your browser's console or in you Craft logs?

**Comment by DidoMarchet** [comment]
Hi,
I premise that I don't use google Login anymore (only Faceboook) and maybe someone other could have my issue.
When I tried the console doesn't gave me errors.

Maybe if I'll retry I can give you more details. 

Thanks for support and regards,

Davide
