### ISSUE TITLE
OAuth redirect_url failing

### ISSUE THREAD

**Issue by RoussKS** [dukt/social#3]
### Description

> Error

`OAuthException: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request`

Trying to set up the plugin on a Craft CMS version mentioned below to use with Craft Commerce. OAuth plugin is installed as well.

We have added the redirect URL that is in Craft's cP to our facebook application
Domains are set for the local environment. As well as setting up the App ID & Secret. However we encounter the error above.

This seems to happen on return to our local website.

is there a specific redirect that needs to be placed on the template files used or anything like that?

First time dealing with facebook API, so please excuse my ignorance on this. I hoped that with simple steps to have it working on local.

FB API version is 2.11, plugin supports up to 2.8 if that's of any use.

Thanks

### Additional info

- Plugin version: 1.2.4
- Craft version: Craft CMS 2.6.2997
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35

**Comment by benjamindavid** [comment]
We've just published [OAuth 2.1.3](https://github.com/dukt/oauth/releases/tag/2.1.3) which should fix an coding issue with Facebook redirect URIs which may fix the redirect uri issue you were having.

[Social 1.2.5](https://github.com/dukt/social/releases/tag/1.2.5) has also been released and bumps Facebook's Graph API default version to v2.12. This release also provides a way to [customize the Graph API version](https://github.com/dukt/social/blob/afbd9e87413ddbcfefd5ec9fe323c071413df25d/config.php#L41).

Closing this for now, feel free to reopen if you're getting errors.
