### ISSUE TITLE
Re-register soft deleted user

### ISSUE THREAD

**Issue by jorenvanhee** [dukt/social#32]
### Description

Logging in via facebook for the "first time" doesn't work if the user had an account before that has been soft deleted. First time a user logs in/registers via facebook, everything works. Delete the user in the control panel and try that again. You then get redirected to facebook like usual. After that, I get redirect to the login page. I'm not logged in. An account has been created though if you look in the control panel.

### Steps to reproduce

1. Log in using facebook for the first time
2. Delete the user in the control panel
3. Try logging in again with the same facebook account

### Additional info

- Plugin version: 2.0
- Craft version: 3.1.17.1
- PHP version: 7.2.5
- Database driver & version: MySQL 5.7.19

**Comment by zesda** [comment]
A temporary work-around to this is to force a run Craft CMS's garbage collector using the following command:

`./craft gc --delete-all-trashed=1`
