### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by migswd** [dukt/social#33]
### Description
The plugin installation gives an error :

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for dukt/social 2.0.0 -> satisfiable by dukt/social[2.0.0].
- Conclusion: remove league/oauth2-google 2.2.0
- dukt/videos 2.0.5 requires league/oauth2-google ^2.2.0 -> satisfiable by league/oauth2-google[2.2.0].
- dukt/videos 2.0.5 requires league/oauth2-google ^2.2.0 -> satisfiable by league/oauth2-google[2.2.0].
- dukt/videos 2.0.5 requires league/oauth2-google ^2.2.0 -> satisfiable by league/oauth2-google[2.2.0].
- Can only install one of: league/oauth2-google[2.2.0, 3.0.0].
- Can only install one of: league/oauth2-google[3.0.0, 2.2.0].
- dukt/social 2.0.0 requires league/oauth2-google ^3.0 -> satisfiable by league/oauth2-google[3.0.0, 3.0.1].
- Conclusion: don't install league/oauth2-google 3.0.1
- Installation request for dukt/videos 2.0.5 -> satisfiable by dukt/videos[2.0.5].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

### Steps to reproduce
1. Click on TRY on the plugin page in the plugin store

### Additional info
- Plugin version: 2.0.0
- Craft version: Craft CMS 3.1.19 (last)
PHP version | 7.3.0
Linux 4.9.124-paas-2270098
MySQL 5.7.23

**Comment by benjamindavid** [comment]
Hey, sorry about that. Could you please share a copy of your `composer.json` file? Thanks!

**Comment by benjamindavid** [comment]
Closing for now, feel free to reopen if you're still having issues.
