### ISSUE TITLE
login with linkedin does not work anymore

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [dukt/social#36]
### Description
The login with dukt/social-linkedin does not work anymore.
Linkedin took it's api v1 out.

Can this be restored or integrated in the dukt social plugin itself?
Logging in with linked in was the only reason I purchased the login for my client

### Steps to reproduce

1. Install dukt social and dukt social linkedin
2. Set up craft to allow logging in / registering with linkedin
3. Login fails

### Additional info

- Plugin version: 
- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by benjamindavid** [comment]
This issue has been fixed and API updated to v1 in [Social LinkedIn 3.0.4](https://github.com/dukt/social-linkedin/blob/v3/CHANGELOG.md#304---2019-06-02). Thanks!
