### ISSUE TITLE
User Avatar File Rename Error

### ISSUE THREAD

**Issue by skayo** [dukt/social#38]
### Description

When I try to login via Twitter, I get the following error (translated from german and replaced some personal stuff):
```
rename(D:\skayo\Documents\Craft\CraftyCoffee\storage\runtime\temp/social/userphotos/test@example.com/photo, D:\skayo\Documents\Craft\CraftyCoffee\storage\runtime\temp/social/userphotos/test@example.com/photo.jpg): The process cannot access the file because it is used by another process. (code: 32)
```

### Steps to reproduce

1. Go to CP Login
2. Try to login with Twitter

### Additional info

- Plugin version: 2.0.1
- Craft version: 3.3.0.1
- PHP version: 7.1

**Comment by Skayo** [comment]
I'm not actually asking you to fix this problem but to just somehow expect this error message in your plugin.

**Comment by renaldypermana** [comment]
I have the same problem, and I still waiting for information on how to fix this
